// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import <Foundation/Foundation.h>
@protocol FlutterBinaryMessenger;
@protocol FlutterMessageCodec;
@class FlutterError;
@class FlutterStandardTypedData;

NS_ASSUME_NONNULL_BEGIN

@class Article;

@interface Article : NSObject
/// `init` unavailable to enforce nonnull fields, see the `make` class method.
- (instancetype)init NS_UNAVAILABLE;
+ (instancetype)makeWithTitle:(NSString *)title
    descr:(NSString *)descr
    urlToImage:(nullable NSString *)urlToImage
    url:(NSString *)url
    publishedAt:(nullable NSString *)publishedAt
    content:(nullable NSString *)content;
@property(nonatomic, copy) NSString * title;
@property(nonatomic, copy) NSString * descr;
@property(nonatomic, copy, nullable) NSString * urlToImage;
@property(nonatomic, copy) NSString * url;
@property(nonatomic, copy, nullable) NSString * publishedAt;
@property(nonatomic, copy, nullable) NSString * content;
@end

/// The codec used by ArticleApi.
NSObject<FlutterMessageCodec> *ArticleApiGetCodec(void);

@protocol ArticleApi
- (void)articlesWithCompletion:(void(^)(NSArray<Article *> *_Nullable, FlutterError *_Nullable))completion;
@end

extern void ArticleApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ArticleApi> *_Nullable api);

NS_ASSUME_NONNULL_END
