// Autogenerated from Pigeon (v2.0.3), do not edit directly.
// See also: https://pub.dev/packages/pigeon
#import "pigeon.h"
#import <Flutter/Flutter.h>

#if !__has_feature(objc_arc)
#error File requires ARC to be enabled.
#endif

static NSDictionary<NSString *, id> *wrapResult(id result, FlutterError *error) {
  NSDictionary *errorDict = (NSDictionary *)[NSNull null];
  if (error) {
    errorDict = @{
        @"code": (error.code ? error.code : [NSNull null]),
        @"message": (error.message ? error.message : [NSNull null]),
        @"details": (error.details ? error.details : [NSNull null]),
        };
  }
  return @{
      @"result": (result ? result : [NSNull null]),
      @"error": errorDict,
      };
}
static id GetNullableObject(NSDictionary* dict, id key) {
  id result = dict[key];
  return (result == [NSNull null]) ? nil : result;
}
static id GetNullableObjectAtIndex(NSArray* array, NSInteger key) {
  id result = array[key];
  return (result == [NSNull null]) ? nil : result;
}


@interface Article ()
+ (Article *)fromMap:(NSDictionary *)dict;
- (NSDictionary *)toMap;
@end

@implementation Article
+ (instancetype)makeWithTitle:(NSString *)title
    descr:(NSString *)descr
    urlToImage:(nullable NSString *)urlToImage
    url:(NSString *)url
    publishedAt:(nullable NSString *)publishedAt
    content:(nullable NSString *)content {
  Article* pigeonResult = [[Article alloc] init];
  pigeonResult.title = title;
  pigeonResult.descr = descr;
  pigeonResult.urlToImage = urlToImage;
  pigeonResult.url = url;
  pigeonResult.publishedAt = publishedAt;
  pigeonResult.content = content;
  return pigeonResult;
}
+ (Article *)fromMap:(NSDictionary *)dict {
  Article *pigeonResult = [[Article alloc] init];
  pigeonResult.title = GetNullableObject(dict, @"title");
  NSAssert(pigeonResult.title != nil, @"");
  pigeonResult.descr = GetNullableObject(dict, @"descr");
  NSAssert(pigeonResult.descr != nil, @"");
  pigeonResult.urlToImage = GetNullableObject(dict, @"urlToImage");
  pigeonResult.url = GetNullableObject(dict, @"url");
  NSAssert(pigeonResult.url != nil, @"");
  pigeonResult.publishedAt = GetNullableObject(dict, @"publishedAt");
  pigeonResult.content = GetNullableObject(dict, @"content");
  return pigeonResult;
}
- (NSDictionary *)toMap {
  return [NSDictionary dictionaryWithObjectsAndKeys:(self.title ? self.title : [NSNull null]), @"title", (self.descr ? self.descr : [NSNull null]), @"descr", (self.urlToImage ? self.urlToImage : [NSNull null]), @"urlToImage", (self.url ? self.url : [NSNull null]), @"url", (self.publishedAt ? self.publishedAt : [NSNull null]), @"publishedAt", (self.content ? self.content : [NSNull null]), @"content", nil];
}
@end

@interface ArticleApiCodecReader : FlutterStandardReader
@end
@implementation ArticleApiCodecReader
- (nullable id)readValueOfType:(UInt8)type 
{
  switch (type) {
    case 128:     
      return [Article fromMap:[self readValue]];
    
    default:    
      return [super readValueOfType:type];
    
  }
}
@end

@interface ArticleApiCodecWriter : FlutterStandardWriter
@end
@implementation ArticleApiCodecWriter
- (void)writeValue:(id)value 
{
  if ([value isKindOfClass:[Article class]]) {
    [self writeByte:128];
    [self writeValue:[value toMap]];
  } else 
{
    [super writeValue:value];
  }
}
@end

@interface ArticleApiCodecReaderWriter : FlutterStandardReaderWriter
@end
@implementation ArticleApiCodecReaderWriter
- (FlutterStandardWriter *)writerWithData:(NSMutableData *)data {
  return [[ArticleApiCodecWriter alloc] initWithData:data];
}
- (FlutterStandardReader *)readerWithData:(NSData *)data {
  return [[ArticleApiCodecReader alloc] initWithData:data];
}
@end

NSObject<FlutterMessageCodec> *ArticleApiGetCodec() {
  static dispatch_once_t sPred = 0;
  static FlutterStandardMessageCodec *sSharedObject = nil;
  dispatch_once(&sPred, ^{
    ArticleApiCodecReaderWriter *readerWriter = [[ArticleApiCodecReaderWriter alloc] init];
    sSharedObject = [FlutterStandardMessageCodec codecWithReaderWriter:readerWriter];
  });
  return sSharedObject;
}


void ArticleApiSetup(id<FlutterBinaryMessenger> binaryMessenger, NSObject<ArticleApi> *api) {
  {
    FlutterBasicMessageChannel *channel =
      [[FlutterBasicMessageChannel alloc]
        initWithName:@"dev.flutter.pigeon.ArticleApi.articles"
        binaryMessenger:binaryMessenger
        codec:ArticleApiGetCodec()        ];
    if (api) {
      NSCAssert([api respondsToSelector:@selector(articlesWithCompletion:)], @"ArticleApi api (%@) doesn't respond to @selector(articlesWithCompletion:)", api);
      [channel setMessageHandler:^(id _Nullable message, FlutterReply callback) {
        [api articlesWithCompletion:^(NSArray<Article *> *_Nullable output, FlutterError *_Nullable error) {
          callback(wrapResult(output, error));
        }];
      }];
    }
    else {
      [channel setMessageHandler:nil];
    }
  }
}
